project_id = "tujborgbqzmcwolntvas"

[functions.admin-login]
verify_jwt = false

[functions.admin-bookings]
verify_jwt = false

[functions.admin-services]
verify_jwt = false

[functions.user-bookings]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.confirm-booking]
verify_jwt = false

[functions.prepare-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.notifications]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.manage-drivers]
verify_jwt = false

[functions.driver-login]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.guide-login]
verify_jwt = false

[functions.manage-guides]
verify_jwt = false

[functions.ai-tourist-guide]
verify_jwt = false
