project_id = "tujborgbqzmcwolntvas"

[functions.admin-login]
verify_jwt = false

[functions.admin-bookings]
verify_jwt = true

[functions.send-booking-email]
verify_jwt = false

[functions.manage-drivers]
verify_jwt = true

[functions.driver-login]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = true

[functions.guide-login]
verify_jwt = false

[functions.manage-guides]
verify_jwt = true

[functions.ai-tourist-guide]
verify_jwt = false